---
- name: Ensure nova flavors exist
  os_nova_flavor:
    auth_type: "{{ os_flavors_auth_type }}"
    auth: "{{ os_flavors_auth }}"
    cacert: "{{ os_flavors_cacert | default(omit) }}"
    interface: "{{ os_flavors_interface | default(omit, true) }}"
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    ephemeral: "{{ item.ephemeral | default(omit) }}"
    swap: "{{ item.swap | default(omit) }}"
    rxtx_factor: "{{ item.rxtx_factor | default(omit) }}"
    is_public: "{{ item.is_public | default(omit) }}"
    flavorid: "{{ item.flavorid | default(omit) }}"
    extra_specs: "{{ item.extra_specs | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ os_flavors }}"
